FROM node:20.12.2
WORKDIR /app

# Важно для кеширования слоев
COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci

# Копируем все файлы проекта (кроме тех, что указаны в .dockerignore)
COPY app/. .

EXPOSE 8080
ENV NODE_ENV=production
RUN make build
